services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - backend
    volumes:
      - './db/data:/data/db'

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    links:
      - mongo
    networks:
      - backend
      - frontend-db-manager

  api:
    build: ./api
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      DB_CONN_STRING: mongodb://root:example@mongo:27017/
      TOKEN_SECRET: tokenSecret
    links:
      - mongo
    networks:
      - frontend
      - backend

  ui:
    build: ./ui
    restart: unless-stopped
    ports:
      - 80:80
    links:
      - api
    environment:
      PORT: 80
    networks:
      - frontend
      - backend

networks:
  frontend-db-manager:
    driver: bridge
  frontend:
    driver: bridge
  backend:
    driver: bridge
